apiVersion: v1
kind: Service
metadata:
  name: abc-in-minion
  labels:
    app: minion
spec:
  ports:
  - port: 8001
    name: inside
  selector:
    app: minion
---
apiVersion: v1
kind: Service
metadata:
  name: abc-out-minion
  labels:
    app: minion
spec:
  ports:
  - port: 8002
    name: outside
  selector:
    app: minion
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: abc-minion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minion
        version: v1
        cluster: "sjc"
        role: minion
    spec:
      containers:
      - name: minion
        image: davigupta/minion:0.65
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        - containerPort: 8002
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            value: "abc"
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_CLUSTER
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['cluster']
         - name: MY_DNS
            value: "10.110.209.4"
         - name: MY_MONGO_URI
            value: "mongodb+srv://nextensio:nextensio238@cluster0.prph0.mongodb.net"
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
---
