# This file is a template, and might need editing before it works on your project.
image: docker:19.03.12

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/nextensio/cluster
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.12-dind

before_script:
  - docker info

stages:
  - build
  - test
  - deploy

compile-and-test:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/nxts.io; docker build -t minion-go .
    - docker run minion-go sh -c 'go fmt $(go list ./... | grep -v /vendor/); go vet $(go list ./... | grep -v /vendor/); go test -race $(go list ./... | grep -v /vendor/ | grep -v consul)'
    - cd $CI_PROJECT_DIR/minion; docker build -t minion-py .