apiVersion: v1
kind: Service
metadata:
  name: bunny-com-in
  namespace: aaa
  labels:
    app: bunny
spec:
  ports:
  - port: 80
    name: bunny-inside
  selector:
    app: bunny
---
apiVersion: v1
kind: Service
metadata:
  name: bunny-com-out
  namespace: aaa
  labels:
    app: bunny
spec:
  ports:
  - port: 8002
    name: bunny-outside
  selector:
    app: bunny
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bunny
  namespace: aaa
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"d884a063f4c12cf8c0608f2e41cddbd24a52db4c91920b90969c5867591a46db","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","ric-credentials","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: bunny
        cluster: sjc
        role: minion
        version: v1
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          value: bunny-com
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_CLUSTER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cluster']
        - name: MY_DNS
          value: 10.110.209.4
        image: davigupta/minion:0.59
        imagePullPolicy: IfNotPresent
        name: minion
        ports:
        - containerPort: 80
        - containerPort: 8002
        resources: {}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - bunny
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_METAJSON_LABELS
          value: |
            {"app":"bunny","cluster":"sjc","role":"minion","version":"v1"}
        image: docker.io/istio/proxyv2:1.0.5
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
        - mountPath: /etc/istio/ric-credentials
          name: ric-credentials
          readOnly: true
      imagePullSecrets:
      - name: regcred
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 80,8002
        - -d
        - ""
        image: docker.io/istio/proxy_init:1.0.5
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: ric-credentials
        secret:
          optional: true
          secretName: ric-credential
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
