apiVersion: v1
kind: Service
metadata:
  name: candy-com-in
  labels:
    app: candy
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: candy
---
apiVersion: v1
kind: Service
metadata:
  name: candy-com-out
  labels:
    app: candy
spec:
  ports:
  - port: 8002
    name: http
  selector:
    app: candy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candy
  template:
    metadata:
      labels:
        app: candy
        version: v1
        cluster: "sjc"
        role: minion
    spec:
      containers:
      - name: minion
        image: davigupta/minion:0.69
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 8002
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          value: "candy-com"
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_CLUSTER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cluster']
        - name: MY_DNS
          value: "10.110.209.4"
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
