apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: consul
spec:
  hosts:
  - "consul.ric.nextensio.net"
  gateways:
  - ric-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host:
          release-name-consul-ui.consul-system.svc.cluster.local
