#
# Author: Davi Gupta (davigupta@gmail.com)
# Copyright May 2019
#
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-ric
  namespace: <pod_namespace>
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  exportTo: ["."]
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: DISABLE
  subsets:
  - name: ric
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-ric-through-egress-mesh
  namespace: <pod_namespace>
spec:
  hosts:
  - <dst_gateway_name>
  exportTo: ["."]
  gateways:
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ric
        port:
          number: 80
      weight: 100
