apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
spec:
  hosts:
  - "jaeger.kismis.org"
  gateways:
  - kismis-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 16686
        host:
          jaeger-query.istio-system.svc.cluster.local
