#
# Author: Davi Gupta (jerrygupta@gmail.com)
# Copyright 2019
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jerry-gw-svc
  namespace: bbb
spec:
  hosts:
  - "gateway.ric.nextensio.net"
  exportTo: ["*"]
  gateways:
  - default/nextensio-ingressgateway
  http:
  - match:
    - headers:
       x-nextensio-for: 
         prefix: "connector-3"
    route:
    - destination:
        host: 
          jerry-com-in
        port:
          number: 80
  - match:
    - headers:
       x-nextensio-connect: 
         prefix: "connector-3"
    route:
    - destination:
        host: 
          jerry-com-out
        port:
          number: 8002
    websocketUpgrade: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jerry-ingress
  namespace: bbb
spec:
  host: jerry-com-in
  exportTo: ["."]
  subsets:
  - name: jerry
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jerry-egress
  namespace: bbb
spec:
  host: jerry-com-out
  exportTo: ["."]
  subsets:
  - name: jerry
