apiVersion: v1
kind: Service
metadata:
  name: jerry-com-in
  namespace: bbb
  labels:
    app: jerry
spec:
  ports:
  - port: 80
    name: jerry-inside
  selector:
    app: jerry
---
apiVersion: v1
kind: Service
metadata:
  name: jerry-com-out
  namespace: bbb
  labels:
    app: jerry
spec:
  ports:
  - port: 8002
    name: jerry-outside
  selector:
    app: jerry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jerry
  namespace: bbb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: '{"version":"6be717f0d9606c8c1257aa2a0f049d957c61378a23ffb0e74424e1e4a517236e","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","sjc-credentials","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: jerry
        cluster: ric
        role: minion
        version: v1
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          value: jerry-com
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_CLUSTER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cluster']
        - name: MY_DNS
          value: 10.100.209.238
        image: davigupta/minion:0.59
        imagePullPolicy: IfNotPresent
        name: minion
        ports:
        - containerPort: 80
        - containerPort: 8002
        resources: {}
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - jerry.$(POD_NAMESPACE)
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15011
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 10s
        - --proxyAdminPort
        - "15000"
        - --concurrency
        - "2"
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
        - --statusPort
        - "15020"
        - --applicationPorts
        - 80,8002
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_METAJSON_LABELS
          value: |
            {"app":"jerry","cluster":"ric","role":"minion","version":"v1"}
        image: docker.io/istio/proxyv2:1.1.2
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15020
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: "2"
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/sjc-credentials
          name: sjc-credentials
          readOnly: true
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      imagePullSecrets:
      - name: regcred
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 80,8002
        - -d
        - "15020"
        image: docker.io/istio/proxy_init:1.1.2
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: sjc-credentials
        secret:
          optional: true
          secretName: sjc-credential
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
status: {}
---
