apiVersion: v1
kind: Service
metadata:
  name: jyoti-com-in
  labels:
    app: jyoti
spec:
  ports:
  - port: 80
    name: http-jyoti-inside
    protocol: TCP
  selector:
    app: jyoti
---
apiVersion: v1
kind: Service
metadata:
  name: jyoti-com-out
  labels:
    app: jyoti
spec:
  ports:
  - port: 8002
    name: http-jyoti-outside
    protocol: TCP
  selector:
    app: jyoti
---
