apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs/data
    server: 192.168.204.20
  persistentVolumeReclaimPolicy: Retain
