#
# Author: Davi Gupta (davigupta@gmail.com)
# Copyright Mar 2019
#
# connect_prefix and fwd_prefix needs to be constructed such that it is unique
# across all namespaces
# suggestion
#  fwd_prefix = <service>:<namespace>
#  connect_prefix = <service>:<namespace>
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: <pod_name>-vs
  namespace: <pod_namespace>
spec:
  hosts:
  - "<src_gateway_name>"
  exportTo: ["*"]
  gateways:
  - <src_gateway_namespace>/nextensio-ingressgateway
  http:
  - match:
    - headers:
        x-nextensio-for: 
          prefix: "<fwd_prefix>"
    route:
    - destination:
        host: 
          <pod_name>-in
        port:
          number: 80
  - match:
    - headers:
        x-nextensio-connect: 
          prefix: "<connect_prefix>"
    route:
    - destination:
        host: 
          <pod_name>-out
        port:
          number: 8002
    websocketUpgrade: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: <pod_name>-ingress
  namespace: <pod_namespace>
spec:
  host: <pod_name>-in
  exportTo: ["."]
  subsets:
  - name: <pod_name>
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: <pod_name>-egress
  namespace: <pod_namespace>
spec:
  host: <pod_name>-out
  exportTo: ["."]
  subsets:
  - name: <pod_name>
