apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-sjc
  namespace: bbb
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  exportTo: ["."]
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: DISABLE
  subsets:
  - name: sjc
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-sjc-through-egress-gateway
  namespace: bbb
spec:
  hosts:
  - gateway.sjc.nextensio.net
  exportTo: ["."]
  gateways:
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: sjc
        port:
          number: 80
      weight: 100
