apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tom-vs
  namespace: default
spec:
  gateways:
  - nextensio-ingressgateway
  hosts: gateway.sjc.nextensio.net
  http:
  - match:
    - headers:
        x-nextensio-for:
          prefix: tom.com
    route:
    - destination:
        host: tom-in
        port:
          number: 80
  - match:
    - headers:
        x-nextensio-connect:
          prefix: tom.com
    route:
    - destination:
        host: tom-out
        port:
          number: 8002
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tom-ingress
  namespace: default
spec:
  host: tom-in
  subsets:
  - labels:
      version: v1
    name: tom
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tom-egress
  namespace: default
spec:
  host: tom-out
  subsets:
  - labels:
      version: v1
    name: tom
