FROM golang:1.13-alpine3.12

MAINTAINER Davi Gupta <davigupta@gmail.com>
COPY files .
WORKDIR /go/src/app
COPY minion.io .
RUN go get -d -v ./... \
    && go install -v ./... \
    && \rm -r -f /go/src/app/* \
    && \rm -r -f /go/pkg/mod \
    && \rm -r -f /go/pkg/sumdb
EXPOSE 80/tcp 8002/tcp
CMD ["/go/bin/minion.io", "-tunnel", "-consul_dns", "-register", "-ip", "127.0.0.1", "-iport", "80"]
